language: ruby

before_install:
  - gem install bundler
    
notifications:
  email:
    recipients:
      - sky4winder+bumper_pusher@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
