language: ruby

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
rvm:
  - 2.3.1

notifications:
  email:
    recipients:
      - sky4winder+bumper_pusher@gmail.com
    on_success: never # [always|never|change]
    on_failure: change # [always|never|change]
